name: scraper

on:
    workflow_dispatch:
    schedule:
        - cron: "0 * * * *" # runs every hour

jobs:
    generate_list:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script
              run: python scraper.py

            - name: create adblocking lists
              run: |
                  sed 's/^/\|\|/;s/$/\^/' ipsniper-info-malicious-urls.txt > ipsniper-info-malicious-urls-ABP.txt
                  sed 's/^/\|\|/;s/$/\^\$all/' ipsniper-info-malicious-urls.txt > ipsniper-info-malicious-urls-UBO.txt

            - name: commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "update blocklist" && git push )
