name: scraper

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */1 * * *" # runs every hour

jobs:
    generate_list:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10" # install the python version needed

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script # run scraper.py to get the latest data
              run: python scraper.py

            - name: create ABP list
              run: |
                  sed 's/^/\|\|/;s/$/\$all/' ipsniper-info-malicious-urls.txt > ipsniper-info-malicious-urls-ABP.txt

            - name: commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "update blocklist" && git push )
